version: '3'

services:
  master:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qazSedcS123
      - MYSQL_REPLICATION_USER=replication
      - MYSQL_REPLICATION_PASSWORD=qwert123
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
    networks:
      - mariadb_network

  slave1:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qazSedcS123
      - MYSQL_REPLICATION_USER=replication
      - MYSQL_REPLICATION_PASSWORD=qwert123
    volumes:
      - ./slave1.cnf:/etc/mysql/conf.d/slave1.cnf
    depends_on:
      - master
    networks:
      - mariadb_network

  slave2:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=qazSedcS123
      - MYSQL_REPLICATION_USER=replication
      - MYSQL_REPLICATION_PASSWORD=qwert123
    volumes:
      - ./slave2.cnf:/etc/mysql/conf.d/slave2.cnf
    depends_on:
      - master
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge